#Handlers or notifiers in Ansible backend

  - name: Start backend service
    tag: deployement
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: backend
      state: restarted
      enabled: true
      