# - name: Configure libraries Server
#   hosts: local
#   connection: local
#   tasks:
#   - name: ansible to install python libraries	#to connect mysql DB, need PyMySQL dependency
#     ansible.builtin.pip:
#       name: 
#       - PyMySQL
#       - cryptography    
#       - boto3
#       - botocore
#       executable: pip3.9

#Dynamic Inventory of running nginx 
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Name: ansible
  # All instances with their state as `running`
  instance-state-name: running
hostnames:
  - private-ip-address
compose:
  ansible_host: private_ip_address



# #RUN:   ansible-inventory -i aws_ec2.yml --graph